---
name: Build fedora-32

on:
  pull_request:
  push:
    paths:
      - 'fedora32/**'
      - '.github/workflows/fedora-32.yml'
  schedule:
    - cron: '0 6 * * 2'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: 'false'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test building image.
        run: cd fedora32 && docker build -t docker-fedora32 .

      - name: Run the built image.
        run: docker run --name test-fedora32 -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-fedora32

      # - name: Verify Ansible is accessible in the built image.
        # run: docker exec --tty test-centos7 env TERM=xterm ansible --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: fedora32/
          file: fedora32/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:32
